name: flashcards_flutter
version: 0.0.1
description: Flutter view of flashcards.

environment:
  sdk: '>=2.0.0 <3.0.0'
  flutter: '>=0.1.4 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.15.7
  cupertino_icons: ^0.1.0
  flashcards_common:
    path: ../common
  meta: ^1.1.6
  flutter_markdown: ^0.2.0
  url_launcher: ^3.0.3
  package_info: ^0.3.2
  cloud_firestore: ^0.7.4
  firebase_auth: ^0.5.19
  google_sign_in: ^3.0.5
  tuple: ^1.0.2
  font_awesome_flutter: ^8.1.0
  rxdart: ^0.19.0
  after_layout: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - packages/flashcards_common/assets/icons/google_logo.png
  fonts:
    - family: 'Lobster'
      fonts:
        - asset: assets/fonts/lobster-v20-latin-regular.ttf
          weight: 400
