name: flashcards_common
version: 0.0.1
description: Common things of flashcards.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: '^1.1.6'
  intl: '^0.15.7'
  tuple: '^1.0.2'
  rxdart: '^0.19.0'

dev_dependencies:
  test: '^1.3.0'
  intl_translation: '0.17.0'
